# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'epochs_psd-ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EpochsPSDWindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1680, 1050)
        Dialog.setMinimumSize(QtCore.QSize(400, 300))
        Dialog.setMaximumSize(QtCore.QSize(1920, 1080))
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.figureLayout = QtWidgets.QVBoxLayout()
        self.figureLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.figureLayout.setObjectName("figureLayout")
        self.verticalLayout_3.addLayout(self.figureLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(125, 20, 125, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setObjectName("frame")
        self.lowerWindowLayout = QtWidgets.QVBoxLayout(self.frame)
        self.lowerWindowLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.lowerWindowLayout.setSpacing(10)
        self.lowerWindowLayout.setObjectName("lowerWindowLayout")
        self.ParametersLayout = QtWidgets.QHBoxLayout()
        self.ParametersLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.ParametersLayout.setSpacing(15)
        self.ParametersLayout.setObjectName("ParametersLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frequencyLabel = QtWidgets.QLabel(self.frame)
        self.frequencyLabel.setMinimumSize(QtCore.QSize(300, 25))
        self.frequencyLabel.setMaximumSize(QtCore.QSize(300, 25))
        self.frequencyLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frequencyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.frequencyLabel.setObjectName("frequencyLabel")
        self.horizontalLayout_2.addWidget(self.frequencyLabel)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.fmin = QtWidgets.QLineEdit(self.frame)
        self.fmin.setObjectName("fmin")
        self.horizontalLayout_7.addWidget(self.fmin)
        self.fmax = QtWidgets.QLineEdit(self.frame)
        self.fmax.setObjectName("fmax")
        self.horizontalLayout_7.addWidget(self.fmax)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(310, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.frequencySlider = QtWidgets.QSlider(self.frame)
        self.frequencySlider.setOrientation(QtCore.Qt.Horizontal)
        self.frequencySlider.setObjectName("frequencySlider")
        self.horizontalLayout_6.addWidget(self.frequencySlider)
        self.horizontalLayout_6.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.vmaxLabel = QtWidgets.QLabel(self.frame)
        self.vmaxLabel.setMinimumSize(QtCore.QSize(300, 25))
        self.vmaxLabel.setMaximumSize(QtCore.QSize(300, 25))
        self.vmaxLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.vmaxLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.vmaxLabel.setObjectName("vmaxLabel")
        self.horizontalLayout_3.addWidget(self.vmaxLabel)
        self.vmin = QtWidgets.QLineEdit(self.frame)
        self.vmin.setObjectName("vmin")
        self.horizontalLayout_3.addWidget(self.vmin)
        self.vmax = QtWidgets.QLineEdit(self.frame)
        self.vmax.setObjectName("vmax")
        self.horizontalLayout_3.addWidget(self.vmax)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.ParametersLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectPlotLabel = QtWidgets.QLabel(self.frame)
        self.selectPlotLabel.setMinimumSize(QtCore.QSize(200, 25))
        self.selectPlotLabel.setMaximumSize(QtCore.QSize(200, 25))
        self.selectPlotLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.selectPlotLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.selectPlotLabel.setObjectName("selectPlotLabel")
        self.horizontalLayout.addWidget(self.selectPlotLabel)
        self.selectPlotType = QtWidgets.QComboBox(self.frame)
        self.selectPlotType.setObjectName("selectPlotType")
        self.horizontalLayout.addWidget(self.selectPlotType)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.displayLabel = QtWidgets.QLabel(self.frame)
        self.displayLabel.setMinimumSize(QtCore.QSize(200, 25))
        self.displayLabel.setMaximumSize(QtCore.QSize(200, 25))
        self.displayLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.displayLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.displayLabel.setObjectName("displayLabel")
        self.horizontalLayout_4.addWidget(self.displayLabel)
        self.displayLog = QtWidgets.QCheckBox(self.frame)
        self.displayLog.setObjectName("displayLog")
        self.horizontalLayout_4.addWidget(self.displayLog)
        self.showSingleEpoch = QtWidgets.QCheckBox(self.frame)
        self.showSingleEpoch.setObjectName("showSingleEpoch")
        self.horizontalLayout_4.addWidget(self.showSingleEpoch)
        self.showMean = QtWidgets.QCheckBox(self.frame)
        self.showMean.setObjectName("showMean")
        self.horizontalLayout_4.addWidget(self.showMean)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.epochsLabel = QtWidgets.QLabel(self.frame)
        self.epochsLabel.setMinimumSize(QtCore.QSize(200, 25))
        self.epochsLabel.setMaximumSize(QtCore.QSize(200, 25))
        self.epochsLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.epochsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.epochsLabel.setObjectName("epochsLabel")
        self.horizontalLayout_5.addWidget(self.epochsLabel)
        self.epochsSlider = QtWidgets.QSlider(self.frame)
        self.epochsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.epochsSlider.setObjectName("epochsSlider")
        self.horizontalLayout_5.addWidget(self.epochsSlider)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.setStretch(2, 1)
        self.ParametersLayout.addLayout(self.verticalLayout_2)
        self.ParametersLayout.setStretch(0, 4)
        self.ParametersLayout.setStretch(1, 1)
        self.lowerWindowLayout.addLayout(self.ParametersLayout)
        self.lowerWindowLayout.setStretch(0, 2)
        self.horizontalLayout_8.addWidget(self.frame)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.recapLabel = QtWidgets.QLabel(Dialog)
        self.recapLabel.setMinimumSize(QtCore.QSize(300, 25))
        self.recapLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        self.recapLabel.setText("")
        self.recapLabel.setObjectName("recapLabel")
        self.verticalLayout_3.addWidget(self.recapLabel)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "PSD Visualizer"))
        self.frequencyLabel.setText(_translate("Dialog", "Frequency Range Display (min - max)"))
        self.vmaxLabel.setText(_translate("Dialog", "Scaling "))
        self.selectPlotLabel.setText(_translate("Dialog", "Select Plot Type  "))
        self.displayLabel.setText(_translate("Dialog", "Display"))
        self.displayLog.setText(_translate("Dialog", "Log Scale"))
        self.showSingleEpoch.setText(_translate("Dialog", "Single Epoch"))
        self.showMean.setText(_translate("Dialog", "Average over Epochs"))
        self.epochsLabel.setText(_translate("Dialog", "Epoch"))
