# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timefreqdialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TimeFreq(object):
    def setupUi(self, TimeFreq):
        TimeFreq.setObjectName("TimeFreq")
        TimeFreq.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(TimeFreq)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(TimeFreq)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.psdTab = QtWidgets.QWidget()
        self.psdTab.setObjectName("psdTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.psdTab)
        self.verticalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalWidget = QtWidgets.QWidget(self.psdTab)
        self.verticalWidget.setObjectName("verticalWidget")
        self.tabLayout1 = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.tabLayout1.setContentsMargins(0, 0, 0, 0)
        self.tabLayout1.setSpacing(6)
        self.tabLayout1.setObjectName("tabLayout1")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.methodLabel = QtWidgets.QLabel(self.verticalWidget)
        self.methodLabel.setMinimumSize(QtCore.QSize(100, 25))
        self.methodLabel.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setItalic(True)
        self.methodLabel.setFont(font)
        self.methodLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.methodLabel.setObjectName("methodLabel")
        self.horizontalLayout.addWidget(self.methodLabel)
        self.psdMethod = QtWidgets.QComboBox(self.verticalWidget)
        self.psdMethod.setMinimumSize(QtCore.QSize(50, 25))
        self.psdMethod.setMaximumSize(QtCore.QSize(16777215, 25))
        self.psdMethod.setAccessibleName("")
        self.psdMethod.setCurrentText("")
        self.psdMethod.setFrame(False)
        self.psdMethod.setObjectName("psdMethod")
        self.horizontalLayout.addWidget(self.psdMethod)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)
        self.tabLayout1.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalWidget)
        self.label_2.setMinimumSize(QtCore.QSize(100, 25))
        self.label_2.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.tabLayout1.addLayout(self.horizontalLayout_2)
        self.psdParametersText = QtWidgets.QTextEdit(self.verticalWidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.psdParametersText.setFont(font)
        self.psdParametersText.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.psdParametersText.setFrameShadow(QtWidgets.QFrame.Plain)
        self.psdParametersText.setLineWidth(1)
        self.psdParametersText.setObjectName("psdParametersText")
        self.tabLayout1.addWidget(self.psdParametersText)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.psdButton = QtWidgets.QPushButton(self.verticalWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.psdButton.setFont(font)
        self.psdButton.setCheckable(False)
        self.psdButton.setObjectName("psdButton")
        self.horizontalLayout_5.addWidget(self.psdButton)
        self.savePsdButton = QtWidgets.QPushButton(self.verticalWidget)
        self.savePsdButton.setObjectName("savePsdButton")
        self.horizontalLayout_5.addWidget(self.savePsdButton)
        self.tabLayout1.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addWidget(self.verticalWidget)
        self.verticalLayout_3.setStretch(0, 1)
        self.tabWidget.addTab(self.psdTab, "")
        self.tfrTab = QtWidgets.QWidget()
        self.tfrTab.setObjectName("tfrTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tfrTab)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.methodLabel_3 = QtWidgets.QLabel(self.tfrTab)
        self.methodLabel_3.setMinimumSize(QtCore.QSize(100, 25))
        self.methodLabel_3.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setItalic(True)
        self.methodLabel_3.setFont(font)
        self.methodLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.methodLabel_3.setObjectName("methodLabel_3")
        self.horizontalLayout_3.addWidget(self.methodLabel_3)
        self.tfrMethodBox = QtWidgets.QComboBox(self.tfrTab)
        self.tfrMethodBox.setMinimumSize(QtCore.QSize(100, 25))
        self.tfrMethodBox.setMaximumSize(QtCore.QSize(16777215, 25))
        self.tfrMethodBox.setAccessibleName("")
        self.tfrMethodBox.setCurrentText("")
        self.tfrMethodBox.setObjectName("tfrMethodBox")
        self.horizontalLayout_3.addWidget(self.tfrMethodBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.tfrTab)
        self.label.setMinimumSize(QtCore.QSize(100, 25))
        self.label.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.tfrParametersText = QtWidgets.QTextEdit(self.tfrTab)
        font = QtGui.QFont()
        font.setItalic(True)
        self.tfrParametersText.setFont(font)
        self.tfrParametersText.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tfrParametersText.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tfrParametersText.setObjectName("tfrParametersText")
        self.verticalLayout_2.addWidget(self.tfrParametersText)
        self.tfrButton = QtWidgets.QPushButton(self.tfrTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.tfrButton.setFont(font)
        self.tfrButton.setObjectName("tfrButton")
        self.verticalLayout_2.addWidget(self.tfrButton)
        self.tabWidget.addTab(self.tfrTab, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(TimeFreq)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TimeFreq)

    def retranslateUi(self, TimeFreq):
        _translate = QtCore.QCoreApplication.translate
        TimeFreq.setWindowTitle(_translate("TimeFreq", "Dialog"))
        self.methodLabel.setText(_translate("TimeFreq", "Method"))
        self.label_2.setText(_translate("TimeFreq", "Parameters"))
        self.psdButton.setText(_translate("TimeFreq", "Open Interactive PSD"))
        self.savePsdButton.setText(_translate("TimeFreq", "Save PSD"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.psdTab), _translate("TimeFreq", "Power Spectrum Density "))
        self.methodLabel_3.setText(_translate("TimeFreq", "Method"))
        self.label.setText(_translate("TimeFreq", "Parameters"))
        self.tfrButton.setText(_translate("TimeFreq", "Open Interactive TFR Window"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tfrTab), _translate("TimeFreq", "Time-Frequency"))
