# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'time_freq.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TimeFreq(object):
    def setupUi(self, MenuWindow):
        MenuWindow.setObjectName("MenuWindow")
        MenuWindow.resize(407, 540)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        MenuWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Time-Frequency-Module/media/main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MenuWindow.setWindowIcon(icon)
        MenuWindow.setAutoFillBackground(False)
        MenuWindow.setStyleSheet("")
        MenuWindow.setDocumentMode(False)
        MenuWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MenuWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MenuWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setContentsMargins(5, 9, 5, 0)
        self.mainLayout.setSpacing(6)
        self.mainLayout.setObjectName("mainLayout")
        self.upper = QtWidgets.QWidget(self.centralwidget)
        self.upper.setObjectName("upper")
        self.UpperLayout = QtWidgets.QVBoxLayout(self.upper)
        self.UpperLayout.setContentsMargins(0, 0, 0, 0)
        self.UpperLayout.setSpacing(6)
        self.UpperLayout.setObjectName("UpperLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalGroupBox = QtWidgets.QGroupBox(self.upper)
        self.verticalGroupBox.setFlat(False)
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.dataLayout_2 = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.dataLayout_2.setObjectName("dataLayout_2")
        self.choosePathLayout = QtWidgets.QHBoxLayout()
        self.choosePathLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.choosePathLayout.setSpacing(10)
        self.choosePathLayout.setObjectName("choosePathLayout")
        self.pathButton = QtWidgets.QPushButton(self.verticalGroupBox)
        self.pathButton.setMinimumSize(QtCore.QSize(50, 25))
        self.pathButton.setMaximumSize(QtCore.QSize(130, 25))
        self.pathButton.setFlat(False)
        self.pathButton.setObjectName("pathButton")
        self.choosePathLayout.addWidget(self.pathButton)
        self.pathLine = QtWidgets.QLineEdit(self.verticalGroupBox)
        self.pathLine.setMinimumSize(QtCore.QSize(50, 25))
        self.pathLine.setMaximumSize(QtCore.QSize(16777215, 25))
        self.pathLine.setFrame(True)
        self.pathLine.setReadOnly(True)
        self.pathLine.setClearButtonEnabled(False)
        self.pathLine.setObjectName("pathLine")
        self.choosePathLayout.addWidget(self.pathLine)
        self.dataLayout_2.addLayout(self.choosePathLayout)
        self.dataFilesBox = QtWidgets.QComboBox(self.verticalGroupBox)
        self.dataFilesBox.setObjectName("dataFilesBox")
        self.dataLayout_2.addWidget(self.dataFilesBox)
        self.groupBox = QtWidgets.QGroupBox(self.verticalGroupBox)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 150))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.infoLabel = QtWidgets.QLabel(self.groupBox)
        self.infoLabel.setText("")
        self.infoLabel.setObjectName("infoLabel")
        self.verticalLayout_2.addWidget(self.infoLabel)
        self.dataLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.plotButton = QtWidgets.QPushButton(self.verticalGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(130)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.plotButton.sizePolicy().hasHeightForWidth())
        self.plotButton.setSizePolicy(sizePolicy)
        self.plotButton.setMinimumSize(QtCore.QSize(50, 25))
        self.plotButton.setMaximumSize(QtCore.QSize(5614651, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.plotButton.setFont(font)
        self.plotButton.setFlat(False)
        self.plotButton.setObjectName("plotButton")
        self.horizontalLayout_9.addWidget(self.plotButton)
        self.channelButton = QtWidgets.QPushButton(self.verticalGroupBox)
        self.channelButton.setObjectName("channelButton")
        self.horizontalLayout_9.addWidget(self.channelButton)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 1)
        self.dataLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8.addWidget(self.verticalGroupBox)
        self.UpperLayout.addLayout(self.horizontalLayout_8)
        self.mainLayout.addWidget(self.upper)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.psdTab = QtWidgets.QWidget()
        self.psdTab.setObjectName("psdTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.psdTab)
        self.verticalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalWidget = QtWidgets.QWidget(self.psdTab)
        self.verticalWidget.setObjectName("verticalWidget")
        self.tabLayout1 = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.tabLayout1.setContentsMargins(0, 0, 0, 0)
        self.tabLayout1.setSpacing(6)
        self.tabLayout1.setObjectName("tabLayout1")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.methodLabel = QtWidgets.QLabel(self.verticalWidget)
        self.methodLabel.setMinimumSize(QtCore.QSize(100, 25))
        self.methodLabel.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setItalic(True)
        self.methodLabel.setFont(font)
        self.methodLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.methodLabel.setObjectName("methodLabel")
        self.horizontalLayout.addWidget(self.methodLabel)
        self.psdMethod = QtWidgets.QComboBox(self.verticalWidget)
        self.psdMethod.setMinimumSize(QtCore.QSize(50, 25))
        self.psdMethod.setMaximumSize(QtCore.QSize(16777215, 25))
        self.psdMethod.setAccessibleName("")
        self.psdMethod.setCurrentText("")
        self.psdMethod.setFrame(False)
        self.psdMethod.setObjectName("psdMethod")
        self.horizontalLayout.addWidget(self.psdMethod)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)
        self.tabLayout1.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalWidget)
        self.label_2.setMinimumSize(QtCore.QSize(100, 25))
        self.label_2.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.tabLayout1.addLayout(self.horizontalLayout_2)
        self.psdParametersText = QtWidgets.QTextEdit(self.verticalWidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.psdParametersText.setFont(font)
        self.psdParametersText.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.psdParametersText.setFrameShadow(QtWidgets.QFrame.Plain)
        self.psdParametersText.setLineWidth(1)
        self.psdParametersText.setObjectName("psdParametersText")
        self.tabLayout1.addWidget(self.psdParametersText)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.psdButton = QtWidgets.QPushButton(self.verticalWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.psdButton.setFont(font)
        self.psdButton.setCheckable(False)
        self.psdButton.setObjectName("psdButton")
        self.horizontalLayout_5.addWidget(self.psdButton)
        self.savePsdButton = QtWidgets.QPushButton(self.verticalWidget)
        self.savePsdButton.setObjectName("savePsdButton")
        self.horizontalLayout_5.addWidget(self.savePsdButton)
        self.tabLayout1.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addWidget(self.verticalWidget)
        self.verticalLayout_3.setStretch(0, 1)
        self.tabWidget.addTab(self.psdTab, "")
        self.tfrTab = QtWidgets.QWidget()
        self.tfrTab.setObjectName("tfrTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tfrTab)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.methodLabel_3 = QtWidgets.QLabel(self.tfrTab)
        self.methodLabel_3.setMinimumSize(QtCore.QSize(100, 25))
        self.methodLabel_3.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setItalic(True)
        self.methodLabel_3.setFont(font)
        self.methodLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.methodLabel_3.setObjectName("methodLabel_3")
        self.horizontalLayout_3.addWidget(self.methodLabel_3)
        self.tfrMethodBox = QtWidgets.QComboBox(self.tfrTab)
        self.tfrMethodBox.setMinimumSize(QtCore.QSize(100, 25))
        self.tfrMethodBox.setMaximumSize(QtCore.QSize(16777215, 25))
        self.tfrMethodBox.setAccessibleName("")
        self.tfrMethodBox.setCurrentText("")
        self.tfrMethodBox.setObjectName("tfrMethodBox")
        self.horizontalLayout_3.addWidget(self.tfrMethodBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.tfrTab)
        self.label.setMinimumSize(QtCore.QSize(100, 25))
        self.label.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.tfrParametersText = QtWidgets.QTextEdit(self.tfrTab)
        font = QtGui.QFont()
        font.setItalic(True)
        self.tfrParametersText.setFont(font)
        self.tfrParametersText.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tfrParametersText.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tfrParametersText.setObjectName("tfrParametersText")
        self.verticalLayout.addWidget(self.tfrParametersText)
        self.tfrButton = QtWidgets.QPushButton(self.tfrTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.tfrButton.setFont(font)
        self.tfrButton.setObjectName("tfrButton")
        self.verticalLayout.addWidget(self.tfrButton)
        self.tabWidget.addTab(self.tfrTab, "")
        self.mainLayout.addWidget(self.tabWidget)
        self.mainLayout.setStretch(0, 1)
        MenuWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MenuWindow)
        self.statusbar.setObjectName("statusbar")
        MenuWindow.setStatusBar(self.statusbar)
        self.actionHow_To = QtWidgets.QAction(MenuWindow)
        self.actionHow_To.setObjectName("actionHow_To")
        self.actionAbout_Parameters = QtWidgets.QAction(MenuWindow)
        self.actionAbout_Parameters.setObjectName("actionAbout_Parameters")
        self.actionConvert_Raw_to_Epochs = QtWidgets.QAction(MenuWindow)
        self.actionConvert_Raw_to_Epochs.setObjectName("actionConvert_Raw_to_Epochs")
        self.actionICA_Toolbox = QtWidgets.QAction(MenuWindow)
        self.actionICA_Toolbox.setObjectName("actionICA_Toolbox")
        self.actionContact_us = QtWidgets.QAction(MenuWindow)
        self.actionContact_us.setObjectName("actionContact_us")
        self.actionCampus_Biotech = QtWidgets.QAction(MenuWindow)
        self.actionCampus_Biotech.setObjectName("actionCampus_Biotech")
        self.actionAbout_the_project = QtWidgets.QAction(MenuWindow)
        self.actionAbout_the_project.setObjectName("actionAbout_the_project")
        self.actionContribute = QtWidgets.QAction(MenuWindow)
        self.actionContribute.setObjectName("actionContribute")

        self.retranslateUi(MenuWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MenuWindow)

    def retranslateUi(self, MenuWindow):
        _translate = QtCore.QCoreApplication.translate
        MenuWindow.setWindowTitle(_translate("MenuWindow", "PSD Frequency Visualizer"))
        self.verticalGroupBox.setTitle(_translate("MenuWindow", "Data"))
        self.pathButton.setText(_translate("MenuWindow", "Path"))
        self.groupBox.setTitle(_translate("MenuWindow", "Informations"))
        self.plotButton.setText(_translate("MenuWindow", "Preview Data"))
        self.channelButton.setText(_translate("MenuWindow", "Select Channels"))
        self.methodLabel.setText(_translate("MenuWindow", "Method"))
        self.label_2.setText(_translate("MenuWindow", "Parameters"))
        self.psdButton.setText(_translate("MenuWindow", "Open Interactive PSD"))
        self.savePsdButton.setText(_translate("MenuWindow", "Save PSD"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.psdTab), _translate("MenuWindow", "Power Spectrum Density "))
        self.methodLabel_3.setText(_translate("MenuWindow", "Method"))
        self.label.setText(_translate("MenuWindow", "Parameters"))
        self.tfrButton.setText(_translate("MenuWindow", "Open Interactive TFR Window"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tfrTab), _translate("MenuWindow", "Time-Frequency"))
        self.actionHow_To.setText(_translate("MenuWindow", "How To Use ? "))
        self.actionAbout_Parameters.setText(_translate("MenuWindow", "About Parameters"))
        self.actionConvert_Raw_to_Epochs.setText(_translate("MenuWindow", "Raw to Epochs Converter"))
        self.actionICA_Toolbox.setText(_translate("MenuWindow", "ICA Toolbox"))
        self.actionContact_us.setText(_translate("MenuWindow", "Contact us !"))
        self.actionCampus_Biotech.setText(_translate("MenuWindow", "About Fondation Campus Biotech Geneva"))
        self.actionAbout_the_project.setText(_translate("MenuWindow", "About the Human Neuroscience Platform"))
        self.actionContribute.setText(_translate("MenuWindow", "Contribute"))
