# © MNELAB developers
#
# License: BSD (3-clause)

from functools import wraps

import pytest

from mnelab.model import Model


class _ValidatingHistory(list):
    """List that checks the complete history after every mutation used by MNELAB."""

    def __init__(self, entries):
        super().__init__(entries)
        self._validate()

    def append(self, entry):
        super().append(entry)
        self._validate()

    def __setitem__(self, key, entry):
        super().__setitem__(key, entry)
        self._validate()

    def _validate(self):
        compile("\n".join(self), "<mnelab-history>", "exec")


@pytest.fixture(autouse=True)
def validate_model_history(monkeypatch):
    """Validate every history generated by models created during a test."""
    model_init = Model.__init__

    @wraps(model_init)
    def init(model, *args, **kwargs):
        model_init(model, *args, **kwargs)
        model.history = _ValidatingHistory(model.history)

    monkeypatch.setattr(Model, "__init__", init)
