name: PySide6 on Linux

on: pull_request

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Linux packages
      run: |
        sudo apt install libxcb-icccm4 libxcb-image0 libxcb-keysyms1 \
                         libxkbcommon-x11-0 xvfb libxcb-randr0 \
                         libxcb-render-util0 libxcb-xinerama0 \
                         libegl1
    - name: Install Python packages
      run: |
        pip install PySide6
    - name: Run tests
      run: |
        xvfb-run python test_pyside6.py
