name: Standalone

on:
  workflow_call:
  workflow_dispatch:
  pull_request:

jobs:
  standalone-macos:
    name: Build macOS standalone
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - name: Install the project
        run: uv sync --all-extras
      - name: Build standalone installer
        working-directory: standalone
        run: uv run python create-standalone-macos.py
      - name: Upload macOS installer
        uses: actions/upload-artifact@v4
        with:
          name: mnelab-macos-installer
          path: standalone/MNELAB-*.dmg

  standalone-windows:
    name: Build Windows standalone
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - name: Install the project
        run: uv sync --all-extras
      - name: Install Inno Setup
        id: inno_setup # Add an ID to this step
        shell: pwsh
        run: |
          winget install --id JRSoftware.InnoSetup --silent --accept-source-agreements --accept-package-agreements
          # Set an output variable with the path
          echo "path=C:\Program Files (x86)\Inno Setup 6" >> $env:GITHUB_OUTPUT
      - name: Debug Inno Setup Path
        shell: pwsh
        run: echo "The Inno Setup path is ${{ steps.inno_setup.outputs.path }}"
      - name: Build standalone installer
        working-directory: standalone
        shell: pwsh
        run: ./create-standalone-windows.ps1
      - name: Upload Windows installer
        uses: actions/upload-artifact@v4
        with:
          name: mnelab-windows-installer
          path: standalone/MNELAB-*.exe