name: Standalone

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      MACOS_CERT_P12_BASE64:
        required: true
      MACOS_CERT_PASSWORD:
        required: true
      AC_USERNAME:
        required: true
      AC_PASSWORD:
        required: true

jobs:
  standalone-macos:
    name: Build macOS standalone
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - name: Install the project
        run: uv sync --all-extras
      - name: Build app bundle
        working-directory: standalone
        run: uv run python create-standalone-macos.py build-app
      - name: Import Developer ID certificate
        run: |
          echo "$MACOS_CERT_P12_BASE64" | base64 --decode > certificate.p12
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "$MACOS_CERT_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
        env:
          MACOS_CERT_P12_BASE64: ${{ secrets.MACOS_CERT_P12_BASE64 }}
          MACOS_CERT_PASSWORD: ${{ secrets.MACOS_CERT_PASSWORD }}
      - name: Code sign MNELAB.app
        run: 'codesign --deep --force --options runtime --sign "Developer ID Application: CLEMENS BRUNNER (9UC2D22DW3)" standalone/dist/MNELAB.app'
      - name: Zip MNELAB.app for notarization
        run: ditto -c -k --sequesterRsrc --keepParent standalone/dist/MNELAB.app MNELAB.zip
      - name: Notarize app
        run: |
          xcrun notarytool submit MNELAB.zip \
            --apple-id "$AC_USERNAME" \
            --password "$AC_PASSWORD" \
            --team-id 9UC2D22DW3 \
            --wait
        env:
          AC_USERNAME: ${{ secrets.AC_USERNAME }}
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
      - name: Staple notarization ticket
        run: xcrun stapler staple standalone/dist/MNELAB.app
      - name: Create DMG from signed and notarized app
        working-directory: standalone
        run: uv run python create-standalone-macos.py build-dmg
      - name: Upload macOS installer
        uses: actions/upload-artifact@v4
        with:
          name: mnelab-macos-installer
          path: standalone/MNELAB-*.dmg

  standalone-windows:
    name: Build Windows standalone
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - name: Install the project
        run: uv sync --all-extras
      - uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install innosetup
      - name: Build standalone installer
        working-directory: standalone
        shell: pwsh
        run: |
          . ..\.venv\Scripts\Activate.ps1
          .\create-standalone-windows.ps1
      - name: Upload Windows installer
        uses: actions/upload-artifact@v4
        with:
          name: mnelab-windows-installer
          path: standalone/MNELAB-*.exe
